export const SDK_VERSION = "0.1.0";

export {
  type MatrixRow,
  type PotError,
  type PotErrorCode,
  type RecoveryAction,
  ALL_CONTRACT_ERROR_SPECS,
  ALL_FOREIGN_ERROR_SPECS,
  FOREIGN_ERROR_ABI,
  classifyError,
  toPotError,
} from "./errors.js";

export {
  type AccountState,
  type EncryptedHandle,
  type EpochPhase,
  type EpochView,
  type PendingWork,
  type PotConfig,
  type PotState,
  EPOCH_PHASES,
  HIDDEN_HANDLE,
  MAX_BATCH_STEPS,
  getPot,
  isUninitialized,
  pendingWork,
  phaseFromUint8,
  readAccount,
  readCurrentEpochId,
  readEpoch,
  readPotConfig,
  readPotState,
} from "./pot.js";

export {
  type DepositFacts,
  type DrawStep,
  type DrawStepAction,
  type EncryptedAmount,
  type FundBlock,
  type FundFacts,
  capHeadroom,
  drawStepFor,
  preflightDeposit,
  preflightFundPrize,
  sendBeginSnapshot,
  sendClaim,
  sendDefundPrize,
  sendDeposit,
  sendDrawStep,
  sendFundPrize,
  sendRequestRandom,
  sendSelectBatch,
  sendSnapshotBatch,
  sendStartNewEpoch,
  sendWithdraw,
  sendWithdrawAll,
} from "./actions.js";
